import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'htx-business-browser-'));
Object.assign(process.env,{NODE_ENV:'test',VERCEL:'1',DATA_BACKEND:'local',HTX_LOCAL_DB_PATH:path.join(dir,'db.json'),SESSION_SECRET:'v30-browser-session-key-test-only-32-characters'});
for(const key of Object.keys(process.env))if(/^(FIREBASE_|GOOGLE_APPLICATION_CREDENTIALS|GOOGLE_SERVICE_ACCOUNT|GOOGLE_SHEETS_)/.test(key))delete process.env[key];
const {db}=await import('../src/firebase-admin.js');
const {hashPassword}=await import('../src/access-policy.js');
await db.collection('users').doc('1').set({id:1,name:'Giám đốc kiểm thử',username:'giamdoc',role:'director',active:true,passwordHash:hashPassword('BrowserDirector-30')});
await db.collection('users').doc('2').set({id:2,name:'Thiết kế A',username:'designer-a',role:'designer',active:true,passwordHash:hashPassword('BrowserDesigner-30'),accessApproved:true,provisionedByDirectorId:'1'});
const {default:app}=await import('../server.js');
const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));
const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100}}),page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
let offline=false;
await context.route('**/*',r=>r.request().url().startsWith(base)&&!(offline&&r.request().url().includes('/api/entity/'))?r.continue():r.abort());
page.on('dialog',d=>d.type()==='prompt'?d.accept(d.defaultValue()):d.accept());
async function set(id,value){const el=page.locator('#'+id);if(await el.evaluate(e=>e.tagName==='SELECT'))await el.selectOption(String(value));else await el.fill(String(value));}
const calc=()=>page.evaluate(()=>calcCurrent());
const state=()=>page.evaluate(async()=>requestV30('/api/state'));
const active=()=>page.waitForSelector('#erpShell:not(.auth-locked)');
try{
 await page.goto(base+'/');await set('loginUsername','giamdoc');await set('loginPassword','BrowserDirector-30');await page.click('#loginBtn');await page.waitForURL('**/app.html#orders');await active();
 await page.evaluate(()=>startProductQuote('other'));
 assert.deepEqual(await page.locator('#otherUnit option').allTextContents(),['Cái','Tấm','Tờ','m²']);
 for(const [id,value] of Object.entries({otherName:'In decal',otherMaterial:'Decal sữa',otherUnit:'m²',otherWidthCm:100,otherHeightCm:100,qty:1,manualUnitPrice:100000,otherFinishing:'Cán mờ',itemNote:'V30 kiểm thử'}))await set(id,value);
 assert.equal((await calc()).total,100000);assert.equal((await calc()).qty,1);
 await set('otherWidthCm',60);await set('otherHeightCm',90);await set('qty',3);assert.equal((await calc()).total,162000);assert.equal((await calc()).qty,1.62);
 for(const unit of ['Cái','Tấm','Tờ']){await set('otherUnit',unit);assert.equal((await calc()).total,300000);}
 await set('otherUnit','m²');await set('manualTotal',100001);assert.equal((await calc()).total,100001);assert.equal((await calc()).unitPrice,100001/1.62);
 await set('manualUnitPrice',100000);await page.click('#addItem');let item=await page.evaluate(()=>state.quoteItems[0]);assert.equal(item.pricingInput.copies,3);assert.equal(item.qty,1.62);
 await page.evaluate(id=>editQuoteItem(id),item.id);assert.equal(await page.inputValue('#qty'),'3');assert.equal(await page.inputValue('#otherWidthCm'),'60');await page.click('#addItem');
 await set('designProductCount',60);assert.equal(await page.inputValue('#designFee'),'2400000');await set('designerId',2);
 await set('customer','Khách Decal V30');await set('customerPhone','0912000030');
 await page.evaluate(()=>{$('vatEnabled').checked=false;renderQuote();});
 await set('depositMode','custom');await set('depositCustomValue',500000);await set('depositCustomUnit','amount');
 await page.screenshot({path:'quote-v30-desktop.png',fullPage:true});
 const saveResponse=page.waitForResponse(r=>r.url().includes('/api/entity/htx_auto_quotes_v5/')&&r.request().method()==='PUT');
 await page.click('#saveOnly');assert.equal((await saveResponse).status(),200);await page.waitForURL('**/app.html#orders');
 let data=await state(),order=data.state.htx_auto_quotes_v5[0];assert.equal(order.total,2562000);assert.equal(order.designProductCount,60);assert.equal(order.designFee,2400000);assert.equal(order.deposit.amount,500000);assert.ok(order.customerId);
 assert.equal(data.state.htx_customer_profiles_v10.length,1);
 assert.ok((await page.locator('.order-receivable').first().textContent()).includes('2.062.000'));
 for(const status of ['Đang in','Gia công sau in','Kiểm tra thành phẩm'])await page.evaluate(async ({id,status})=>setOrderStatus(id,status),{id:order.id,status});
 await page.evaluate(()=>{for(let i=0;i<6;i++)renderCustomers();});assert.equal((await state()).state.htx_customer_profiles_v10.length,1);
 await page.reload();await active();assert.equal((await state()).state.htx_customer_profiles_v10.length,1);
 await page.screenshot({path:'orders-v30-desktop.png',fullPage:true});
 await page.evaluate(async id=>completeDesignV30(String(id)),order.id);
 data=await state();order=data.state.htx_auto_quotes_v5[0];assert.equal(order.designWork.count,60);
 await page.evaluate(async id=>completeDesignV30(String(id)),order.id);assert.equal((await db.collection('designCompletions').get()).size,1);
 const month=order.designWork.month;
 await page.evaluate(month=>{navigate('payroll');$('payrollMonth').value=month;openPayrollModal();},month);
 await set('payrollEmployeeId',2);await page.waitForFunction(()=>document.getElementById('payKpiBonus').value==='300000');
 await set('payBaseSalary',5000000);await set('payStandardDays',26);await set('payWorkedDays',26);await page.uncheck('#payInsuranceEnabled');
 assert.equal(await page.evaluate(()=>payrollCalc(collectPayrollForm()).net),5300000);
 assert.ok((await page.locator('#designKpiInfoV30').textContent()).includes('Không đạt KPI'));
 await page.screenshot({path:'payroll-v30-desktop.png',fullPage:true});await page.evaluate(()=>savePayrollRecord());
 const payroll=(await state()).state.htx_payroll_v17[month][0];assert.equal(payroll.kpiBonus,300000);assert.equal(payroll.designKpi.count,60);
 await page.evaluate(async()=>{await hydrateFromBackend();});
 await page.evaluate(id=>{openPayrollModal(id);},payroll.id);assert.equal(await page.inputValue('#payKpiBonus'),'300000');await page.evaluate(()=>closePayrollModal());
 await page.evaluate(()=>navigate('orders'));
 offline=true;await page.evaluate(async id=>setOrderStatus(id,'Đã giao'),order.id);
 assert.equal(await page.locator('#pendingV30').isVisible(),true);
 const drafts=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('htx_pending_v30_')));assert.ok(drafts.length);assert.ok(drafts.every(([,v])=>!v.includes('Đã giao')));
 offline=false;await page.reload();await active();await page.waitForFunction(()=>v30Sync.ops.size>0);await page.evaluate(()=>retryPendingV30());
 assert.equal((await state()).state.htx_auto_quotes_v5[0].status,'Đã giao');assert.equal(await page.evaluate(()=>v30Sync.ops.size),0);
 const batch=db.batch();for(let i=0;i<305;i++)batch.set(db.collection('orders').doc(String(700000+i)),{id:700000+i,total:i,customer:'Lưu trữ '+i,status:'Tiếp nhận file',version:1,createdAt:'01/01/2026'});await batch.commit();
 await page.evaluate(async()=>hydrateFromBackend());assert.equal(await page.evaluate(()=>getHistory().length),306);
 await page.evaluate(async()=>setOrderStatus(700000,'Đang in'));assert.equal((await db.collection('orders').get()).size,306);
 await page.reload();await active();assert.equal(await page.evaluate(()=>getHistory().length),306);
 await page.evaluate(()=>navigate('accounts'));const downloadPromise=page.waitForEvent('download');await page.evaluate(()=>backupBusinessV30());const download=await downloadPromise;const filename=path.join(dir,'backup.json');await download.saveAs(filename);
 const backup=JSON.parse(fs.readFileSync(filename));assert.equal(backup.counts.orders,306);assert.equal(backup.collections.users,undefined);assert.equal(backup.counts.designCompletions,1);
 assert.ok(!JSON.stringify(backup).includes('BrowserDirector-30'));
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>startProductQuote('other'));await set('otherUnit','m²');await set('otherMaterial','Canvas');await set('otherWidthCm',100);await set('otherHeightCm',100);await set('manualUnitPrice',100000);
 await page.screenshot({path:'quote-v30-mobile.png',fullPage:true});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('PASS V30 browser: cm/m², all units, exact totals, edit/reload, receivables/deposit, customer link, completion ledger, payroll KPI, encrypted pending edit through F5, 306 orders, data backup, mobile.');
}catch(err){console.error('Browser errors:',errors);await page.screenshot({path:'failure-v30.png',fullPage:true});console.error('Page body:',(await page.locator('body').innerText()).slice(-12000));throw err;}
finally{await browser.close();server.closeAllConnections?.();await new Promise(r=>server.close(r));fs.rmSync(dir,{recursive:true,force:true});}
