import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'htx-browser-test-'));
process.env.HTX_LOCAL_DB_PATH=path.join(directory,'database.json');
process.env.SESSION_SECRET='browser-test-only-session-secret-htx-v28';
process.env.VERCEL='1'; process.env.NODE_ENV='test';
for(const key of Object.keys(process.env))if(/^(FIREBASE_|GOOGLE_APPLICATION_CREDENTIALS|GOOGLE_SERVICE_ACCOUNT|GOOGLE_SHEETS_)/.test(key))delete process.env[key];
const {db}=await import('../src/firebase-admin.js');
const {hashPassword}=await import('../src/access-policy.js');
await db.collection('users').doc('202609190001').set({id:202609190001,username:'giamdoc',name:'Giám đốc',role:'director',active:true,passwordHash:hashPassword('BrowserDirector-28')});
const {default:app}=await import('../server.js');
const server=app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));
const base=`http://127.0.0.1:${server.address().port}`;
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1352,height:998}});
const errors=[];
page.on('pageerror',err=>errors.push(err.message));
await page.route('**/*',route=>route.request().url().startsWith(base)?route.continue():route.abort());
try {
  await page.goto(base+'/');
  assert.equal(await page.locator('#loginForm').isVisible(),true);
  assert.equal(await page.getByText('Đăng nhập nhanh',{exact:false}).count(),0);
  assert.equal(await page.locator('#showCreateFirstBtn').count(),0);
  await page.evaluate(()=>{localStorage.setItem('htx_cached_user',JSON.stringify({username:'giamdoc',role:'director'}));localStorage.setItem('htx_session_token','forged');});
  await page.goto(base+'/app.html');await page.waitForURL(base+'/');
  await page.fill('#loginUsername','giamdoc');await page.fill('#loginPassword','wrong-password');await page.click('#loginBtn');
  await page.waitForFunction(()=>document.getElementById('authMsg').textContent.includes('không đúng'));
  assert.equal(await page.locator('#loginForm').isVisible(),true);
  await page.screenshot({path:'login-v28-desktop.png',fullPage:true});
  await page.fill('#loginPassword','BrowserDirector-28');await page.click('#loginBtn');
  await page.waitForURL('**/app.html#orders');await page.waitForSelector('#erpShell:not(.auth-locked)');
  await page.reload();await page.waitForSelector('#erpShell:not(.auth-locked)');
  await page.click('.nav-btn[data-page="accounts"]');
  await page.fill('#newAccountName','Nhân viên kiểm thử');await page.fill('#newAccountUsername','browser-sales');
  await page.fill('#newAccountPassword','BrowserEmployee-28');await page.selectOption('#newAccountRole','sales');
  const saved=page.waitForResponse(res=>res.url().endsWith('/api/admin/users')&&res.request().method()==='POST');
  await page.click('#createAccountBtn');assert.equal((await saved).status(),201);
  await page.waitForFunction(()=>document.getElementById('accountsBody').textContent.includes('browser-sales'));
  await page.click('#logoutBtn');await page.waitForURL(base+'/');
  await page.goto(base+'/app.html');await page.waitForURL(base+'/');
  await page.fill('#loginUsername','browser-sales');await page.fill('#loginPassword','BrowserEmployee-28');await page.click('#loginBtn');
  await page.waitForURL('**/app.html#orders');await page.waitForSelector('#erpShell:not(.auth-locked)');
  assert.equal(await page.locator('.nav-btn[data-page="accounts"]').isVisible(),false);
  assert.equal(await page.locator('.nav-btn[data-page="payroll"]').isVisible(),false);
  assert.equal(await page.locator('.nav-btn[data-page="orders"]').isVisible(),true);
  await page.click('#logoutBtn');await page.waitForURL(base+'/');
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'login-v28-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[]);
  console.log('PASS browser: login first, forged cache blocked, wrong password blocked, director login, refresh, server-side account creation, role-based navigation, logout, mobile layout.');
} finally {
  await browser.close();await new Promise(resolve=>server.close(resolve));fs.rmSync(directory,{recursive:true,force:true});
}
